### ISSUE TITLE
Adding BMC  with system-id BMC  not displaying proper managers URI 

### ISSUE THREAD

**Issue by jeevan-kamkar** [ODIM-Project/ODIM#398] opened 2021-02-16 05:22 UTC
Adding BMC with systemid= BMC should display system URI of added BMC as `/redfish/v1/Managers/UUID:BMC` instead it's giving system URI as `/redfish/v1/Managers/BMC`

**Comment by shivacharanms** [comment] 2021-02-18 10:12
Unable to reproduce in our systems, please provide access to your environment.

**Comment by bharath-b-hpe** [comment] 2021-08-10 11:21
Issue is not reproducible and is working as expected, hence closing this issue.

**Closed by bharath-b-hpe** 2021-08-10 11:21 UTC
Labels: type:bug, status:deferred, prio:normal
