### ISSUE TITLE
copy /odimra/plugin-redfish/plugin-redfish /bin failed

### ISSUE THREAD

**Issue by jaymainal** [ODIM-Project/ODIM#307] opened 2020-12-25 07:58 UTC
Hi

I am trying to install the ODIM.
It shows copy failed as the title when I run "make all".
It fails on make grf_plugin process
I did not see the /odimra/plugin-redfish/plugin-redfish in the source.
Could you help check the issue?

Thanks

**Comment by Bharath-KKB** [comment] 2021-01-05 10:14
Hi Jay we will look into this issue and get back.

**Comment by rahulroshan-kachchap** [comment] 2021-01-05 10:35
Hi @jaymainal can you please provide the console logs after make all command and and post it here. 
It will be easy for us to find out the root cause for this. Thank You

**Comment by jaymainal** [comment] 2021-01-07 03:20
I did not see the issue after I reinstall it in another environment again.
Sorry and please help close the issue, thanks.

**Comment by Bharath-KKB** [comment] 2021-01-07 08:18
CLosing as per Jays comment

**Closed by Bharath-KKB** 2021-01-07 08:18 UTC
